exclude_patterns:
    - config/
    - db/
    - lib/
    - dist/
    - features/
    - ./**/node_modules/
    - script/
    - ./**/spec/
    - ./**/test/
    - ./**/tests/
    - Tests/
    - ./**/vendor/
    - ./**/*_test.go
    - ./**/*.d.ts
