name: CI
on:
    push:
    pull_request:
jobs:
    commit-check:
        name: Check Conventional Commit
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check Conventional Commit
              uses: webiny/action-conventional-commits@v1.1.0
    markdown-link-check:
        name: Check Markdown Links
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check markdown links
              uses: gaurav-nelson/github-action-markdown-link-check@v1
    build:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: './.github/actions/ci-node-setup'
              with:
                  node-version-file: .nvmrc

            - name: Build
              run: npm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: lib
    lint:
        name: Lint
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: './.github/actions/ci-node-setup'
              with:
                  node-version-file: .nvmrc

            - name: Lint
              run: npm run lint
            - name: Format
              run: npm run format
    test:
        name: Test
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node: [14, 16, lts/-1, lts/*, latest]
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node (${{ matrix.node }})
              uses: './.github/actions/ci-node-setup'
              with:
                  node-version: ${{ matrix.node }}

            - name: Test (With Coverage)
              run: npm run test:coverage
            - name: Upload test artifacts
              uses: actions/upload-artifact@v3
              if: success() || failure()
              with:
                  name: test-results-${{ matrix.node }}
                  path: test/junit.xml
            - name: Upload coverage artifacts
              uses: actions/upload-artifact@v3
              if: success() || failure()
              with:
                  name: test-coverage-${{ matrix.node }}
                  path: coverage/cobertura-coverage.xml
            - name: Upload coverage reports to Codeclimate
              uses: paambaati/codeclimate-action@v4.0.0
              env:
                  CC_TEST_REPORTER_ID: 58fee0878c31e85a459cb081232fb69f843bf41b49d4ddf5bfd89373bbba0e81
              with:
                  coverageLocations: |
                      coverage/cobertura-coverage.xml:cobertura
    process-test-output:
        runs-on: ubuntu-22.04
        needs: test
        if: success() || failure()
        steps:
            - uses: actions/checkout@v3
            - name: Download test artifacts
              uses: actions/download-artifact@v3
              with:
                  path: test
            - name: List test artifacts
              run: ls -la test
