name: Coverage Report
on:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
jobs:
  report:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-coverage
          path: coverage
      - name: Create coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          path: 'coverage/*.xml'
          minimum_coverage: 90
          fail_below_threshold: true
          skip_covered: false
          only_changed_files: false