name: Coverage Report
on:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
jobs:
  report:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Create coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          artifact: test-coverage
          name: Coverage Report
          path: '*.xml'
          skip_covered: false
          only_changed_files: false