name: Coverage Report
on:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
jobs:
  report:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Get coverage artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI.yml
          name: test-coverage
          path: coverage
          run_id: ${{ github.event.workflow_run.id }}
      - name: Create coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          path: 'coverage/*.xml'
          minimum_coverage: 90
          fail_below_threshold: true
          skip_covered: false
          only_changed_files: false