name: Test Report
on:
  push:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
jobs:
  report:
    name: Test Report
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: Test Report
          path: '*.xml'
          fail-on-error: false
          reporter: jest-junit